version: '3'

services:
  image_caption_workspace_oikawa:
    image: image_caption_workspace_oikawa
    build:
      context: ./
      dockerfile: docker/workspace/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - nvidia_driver_375.66:/usr/local/nvidia:ro
      - ./:/workspace
    working_dir: "/workspace"
    tty: true
  python:
    depends_on:
      - image_caption_workspace_oikawa
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - nvidia_driver_375.66:/usr/local/nvidia:ro
      - ./:/workspace
    working_dir: "/workspace"
volumes:
  nvidia_driver_375.66:
      external: true