version: '3'

services:
  image_caption_workspace_oikawa:
    image: image_caption_workspace_oikawa
    build:
      context: ./
      dockerfile: docker/workspace/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: "/workspace"
    tty: true
    command: nvidia-smi
  python:
    depends_on:
      - image_caption_workspace_oikawa
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/workspace
    working_dir: "/workspace"
